[package]
name = "rizzoo"
version = "0.6.7"
edition = "2024"
authors = ["plgbrlism"]

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
ctrlc = "3.5.2"
directories = "6.0.0"
image = "0.25.10"
log = "0.4.33"
mcu-material-color = "0.2.2"
notify = "8.2.0"
serde = { version = "1.0.229", features = ["serde_derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
tabled = { version = "0.21.0", features = ["ansi"] }
thiserror = "2.0.19"
toml = "1.1.4"
ureq = "3.3.0"
winnow = "1.0.4"
yansi = "1.0.1"

[dev-dependencies]
tempfile = "3.27.0"
