Output assets/showcase.gif
Set Width 1060
Set Height 320
Set FontSize 14
Set FontFamily "JetBrainsMono NFM"
Set Theme "Dracula"
Set TypingSpeed 120ms

Hide
Type "clear"
Enter
Show
Type "rizzoo -i "
Type "~/Pictures/funmehmehs/dank-shrek.jpg"
Type " -p"
Sleep 1s
Enter
Wait+Screen /\[INFO/
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Up
Sleep 1s
Up
Sleep 1s
Enter
ScrollUp 74
Sleep 3s
ScrollDown 74
Sleep 3s

Hide
Type "clear"
Enter
Show
Type "rizzoo -u "
Type "https://w.wallhaven.cc/full/ox/wallhaven-oxmzj5.png "
Type "-S vibrant "
Type "-p"
Enter
Wait+Screen /\[INFO/
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Up
Sleep 1s
Up
Sleep 1s
Enter
ScrollUp 74
Sleep 3s
ScrollDown 74
Sleep 3s

Hide
Type "clear"
Enter
Show
Type "rizzoo -u "
Type "https://w.wallhaven.cc/full/ox/wallhaven-oxmzj5.png "
Type "-S vibrant "
Type "-b fruit-salad "
Type "-p "
Type "--open-picker"
Enter
Wait+Screen /\[INFO/
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Up
Sleep 1s
Up
Sleep 1s
Up
Sleep 1s
Enter
ScrollUp 74
Sleep 3s
ScrollDown 74
Sleep 3s

Hide
Type "clear"
Enter
Show
Type "rizzoo -c "
Type '"#BF00FF"'
Type " -p"
Sleep 1s
Enter
Wait+Screen /\[INFO/
Sleep 1s
ScrollUp 74
Sleep 3s
ScrollDown 74
Sleep 3s




